import type { NextPage } from "next";
import Head from "next/head";
import Sidebar from "../components/Sidebar";
import "E:/chat-app-sic/styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chat App SIC</title>
        <meta name="description" content="Generated by Henry Web Dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
    </div>
  );
};

export default Home;
